/**
 * KARIMO GitHub Module Tests
 *
 * Tests for GitHub operations including gh CLI execution, authentication,
 * PR body generation, and error handling. Uses mocked gh commands
 * where actual GitHub access is not available.
 */

import { describe, expect, test, mock, beforeEach } from 'bun:test'

import {
  GhAuthError,
  GhCliNotFoundError,
  GhCommandError,
  OctokitError,
  PrCreateError,
  RepoAccessError,
  buildPrBody,
  resetAuthCache,
  resetGhAvailabilityCache,
} from '../index'
import type { PrBodyContext } from '../types'

// =============================================================================
// Test Fixtures
// =============================================================================

const MINIMAL_PR_CONTEXT: PrBodyContext = {
  taskId: '1a',
  phaseId: 'phase-1',
  complexity: 5,
  costCeiling: 15,
  description: 'Implement user authentication',
  files: ['src/auth.ts', 'src/middleware.ts'],
}

const FULL_PR_CONTEXT: PrBodyContext = {
  ...MINIMAL_PR_CONTEXT,
  cautionFiles: ['src/auth.ts'],
  successCriteria: ['Tests pass', 'Build succeeds', 'No security vulnerabilities'],
}

// =============================================================================
// Setup
// =============================================================================

beforeEach(() => {
  // Reset caches between tests
  resetAuthCache()
  resetGhAvailabilityCache()
})

// =============================================================================
// PR Body Generation Tests
// =============================================================================

describe('buildPrBody', () => {
  test('generates minimal PR body', () => {
    const body = buildPrBody(MINIMAL_PR_CONTEXT)

    expect(body).toContain('## :robot: KARIMO Automated PR')
    expect(body).toContain('**Task:** 1a')
    expect(body).toContain('**Phase:** phase-1')
    expect(body).toContain('**Complexity:** 5/10')
    expect(body).toContain('**Cost Ceiling:** $15')
    expect(body).toContain('### Changes')
    expect(body).toContain('Implement user authentication')
    expect(body).toContain('### Files Affected')
    expect(body).toContain('`src/auth.ts`')
    expect(body).toContain('`src/middleware.ts`')
    expect(body).toContain('### Validation')
    expect(body).toContain('*Generated by [KARIMO]')
  })

  test('includes caution files section when present', () => {
    const body = buildPrBody(FULL_PR_CONTEXT)

    expect(body).toContain('### Caution Files :warning:')
    expect(body).toContain('`src/auth.ts`')
    expect(body).toContain('require careful review')
  })

  test('includes success criteria when present', () => {
    const body = buildPrBody(FULL_PR_CONTEXT)

    expect(body).toContain('### Success Criteria')
    expect(body).toContain('- [ ] Tests pass')
    expect(body).toContain('- [ ] Build succeeds')
    expect(body).toContain('- [ ] No security vulnerabilities')
  })

  test('omits caution files section when empty', () => {
    const body = buildPrBody(MINIMAL_PR_CONTEXT)

    expect(body).not.toContain('### Caution Files')
    expect(body).not.toContain(':warning:')
  })

  test('omits success criteria section when empty', () => {
    const body = buildPrBody(MINIMAL_PR_CONTEXT)

    expect(body).not.toContain('### Success Criteria')
  })

  test('handles empty files array', () => {
    const context: PrBodyContext = {
      ...MINIMAL_PR_CONTEXT,
      files: [],
    }
    const body = buildPrBody(context)

    expect(body).toContain('### Files Affected')
    expect(body).toContain('_No files affected_')
  })

  test('includes validation checklist', () => {
    const body = buildPrBody(MINIMAL_PR_CONTEXT)

    expect(body).toContain('- [ ] `bun run build` passes')
    expect(body).toContain('- [ ] `bun run typecheck` passes')
    expect(body).toContain('- [ ] `bun run lint` passes')
  })

  test('includes KARIMO footer', () => {
    const body = buildPrBody(MINIMAL_PR_CONTEXT)

    expect(body).toContain('---')
    expect(body).toContain('*Generated by [KARIMO](https://github.com/opensesh/KARIMO)*')
  })
})

// =============================================================================
// Error Class Tests
// =============================================================================

describe('GhCliNotFoundError', () => {
  test('includes installation instructions', () => {
    const error = new GhCliNotFoundError()
    expect(error.name).toBe('GhCliNotFoundError')
    expect(error.message).toContain('GitHub CLI (gh) not found')
    expect(error.message).toContain('https://cli.github.com')
    expect(error.message).toContain('gh auth login')
  })
})

describe('GhAuthError', () => {
  test('includes reason and host', () => {
    const error = new GhAuthError('Token expired', 'github.com')
    expect(error.name).toBe('GhAuthError')
    expect(error.message).toContain('GitHub authentication failed')
    expect(error.message).toContain('github.com')
    expect(error.message).toContain('Token expired')
    expect(error.message).toContain('gh auth login')
  })

  test('works without host', () => {
    const error = new GhAuthError('Not logged in')
    expect(error.message).toContain('Not logged in')
    expect(error.message).not.toContain('for undefined')
  })
})

describe('GhCommandError', () => {
  test('includes command and stderr', () => {
    const error = new GhCommandError(
      ['pr', 'create', '--title', 'Test'],
      1,
      'error: not found'
    )
    expect(error.name).toBe('GhCommandError')
    expect(error.args).toEqual(['pr', 'create', '--title', 'Test'])
    expect(error.exitCode).toBe(1)
    expect(error.stderr).toBe('error: not found')
    expect(error.message).toContain('gh pr create --title Test')
    expect(error.message).toContain('Exit code: 1')
    expect(error.message).toContain('error: not found')
  })
})

describe('PrCreateError', () => {
  test('includes head, base, and reason', () => {
    const error = new PrCreateError('feature/task-1', 'main', 'Branch has no commits ahead')
    expect(error.name).toBe('PrCreateError')
    expect(error.head).toBe('feature/task-1')
    expect(error.base).toBe('main')
    expect(error.reason).toBe('Branch has no commits ahead')
    expect(error.message).toContain('feature/task-1')
    expect(error.message).toContain('main')
    expect(error.message).toContain('Branch has no commits ahead')
  })
})

describe('OctokitError', () => {
  test('includes status and message', () => {
    const error = new OctokitError(404, 'Not Found')
    expect(error.name).toBe('OctokitError')
    expect(error.status).toBe(404)
    expect(error.message).toContain('Status: 404')
    expect(error.message).toContain('Not Found')
  })

  test('includes documentation URL when provided', () => {
    const error = new OctokitError(
      403,
      'Resource not accessible',
      'https://docs.github.com/rest/reference'
    )
    expect(error.message).toContain('https://docs.github.com/rest/reference')
  })
})

describe('RepoAccessError', () => {
  test('includes owner, repo, and reason', () => {
    const error = new RepoAccessError('opensesh', 'private-repo', 'Permission denied')
    expect(error.name).toBe('RepoAccessError')
    expect(error.owner).toBe('opensesh')
    expect(error.repo).toBe('private-repo')
    expect(error.reason).toBe('Permission denied')
    expect(error.message).toContain('opensesh/private-repo')
    expect(error.message).toContain('Permission denied')
  })
})

// =============================================================================
// Type Export Tests
// =============================================================================

describe('Type Exports', () => {
  test('PrBodyContext type is usable', () => {
    const context: PrBodyContext = {
      taskId: 'test',
      phaseId: 'phase-1',
      complexity: 3,
      costCeiling: 10,
      description: 'Test description',
      files: ['test.ts'],
    }
    expect(context.taskId).toBe('test')
  })
})

// =============================================================================
// Integration-Ready Tests (skipped without actual gh CLI)
// =============================================================================

describe('gh CLI Integration', () => {
  // These tests verify the module structure works
  // Actual gh execution tests require gh CLI to be installed

  test('ghExec module exports correctly', async () => {
    // Import to verify exports work
    const { ghExec, isGhAvailable } = await import('../exec')
    expect(typeof ghExec).toBe('function')
    expect(typeof isGhAvailable).toBe('function')
  })

  test('cli-auth module exports correctly', async () => {
    const { verifyGhAuth, getAuthenticatedUsername } = await import('../cli-auth')
    expect(typeof verifyGhAuth).toBe('function')
    expect(typeof getAuthenticatedUsername).toBe('function')
  })

  test('client module exports correctly', async () => {
    const { createGitHubClient, hasGitHubToken } = await import('../client')
    expect(typeof createGitHubClient).toBe('function')
    expect(typeof hasGitHubToken).toBe('function')
  })

  test('pr module exports correctly', async () => {
    const { createPullRequest, getPrStatus, buildPrBody } = await import('../pr')
    expect(typeof createPullRequest).toBe('function')
    expect(typeof getPrStatus).toBe('function')
    expect(typeof buildPrBody).toBe('function')
  })
})

// =============================================================================
// hasGitHubToken Tests
// =============================================================================

describe('hasGitHubToken', () => {
  test('function exists and returns boolean', async () => {
    const { hasGitHubToken } = await import('../client')
    const result = await hasGitHubToken()
    expect(typeof result).toBe('boolean')
  })
})

// =============================================================================
// Barrel Export Tests
// =============================================================================

describe('Barrel Exports', () => {
  test('exports all error classes', async () => {
    const exports = await import('../index')
    expect(exports.KarimoGitHubError).toBeDefined()
    expect(exports.GhCliNotFoundError).toBeDefined()
    expect(exports.GhAuthError).toBeDefined()
    expect(exports.GhCommandError).toBeDefined()
    expect(exports.PrCreateError).toBeDefined()
    expect(exports.OctokitError).toBeDefined()
    expect(exports.RepoAccessError).toBeDefined()
  })

  test('exports all functions', async () => {
    const exports = await import('../index')
    // exec
    expect(typeof exports.isGhAvailable).toBe('function')
    expect(typeof exports.ghExec).toBe('function')
    expect(typeof exports.ghExecJson).toBe('function')
    expect(typeof exports.getGhToken).toBe('function')
    // cli-auth
    expect(typeof exports.verifyGhAuth).toBe('function')
    expect(typeof exports.verifyRepoAccess).toBe('function')
    expect(typeof exports.getAuthenticatedUsername).toBe('function')
    // client
    expect(typeof exports.createGitHubClient).toBe('function')
    expect(typeof exports.hasGitHubToken).toBe('function')
    // pr
    expect(typeof exports.buildPrBody).toBe('function')
    expect(typeof exports.createPullRequest).toBe('function')
    expect(typeof exports.getPrStatus).toBe('function')
    expect(typeof exports.addLabels).toBe('function')
    expect(typeof exports.removeLabels).toBe('function')
    expect(typeof exports.closePr).toBe('function')
    expect(typeof exports.reopenPr).toBe('function')
    expect(typeof exports.markReadyForReview).toBe('function')
  })
})
